version: '3.8'
services:
    api:
        build: .
        container_name: actor_search_api
        restart: on-failure
        volumes:
            - ./app/:/app
        working_dir: /app
        ports:
            - "3000:3000"
        command: npm run start:dev
        networks:
            - actor_search
    web:
        image: library/node:20
        container_name: actor_search_web
        restart: on-failure
        volumes:
            - ./web/:/app
        working_dir: /app
        ports:
            - "80:3000"
        command: npm run start
        networks:
            - actor_search
networks:
    actor_search:
        driver: bridge
